### ISSUE TITLE
[0.25pt] Change OAuth title

### ISSUE THREAD

**Issue by koppor** [adr/adr-manager#43]
![grafik](https://user-images.githubusercontent.com/1366654/101278406-53d7dd80-37bb-11eb-8041-9226dd0458a8.png)

The yellow marked part should be "ADR-Manager", shouldn't it? I think, I have to configure something so that long-term maintenance is ensured?

**Comment by manuelmerkel** [comment]
Has been fixed in the current pull request (#53 )

**Comment by koppor** [comment]
The button still shows something strange:

![grafik](https://user-images.githubusercontent.com/1366654/102526997-c76fc980-409c-11eb-9367-a73d92b93aa2.png)

**Comment by xJREB** [comment]
This was implemented while switching the Pizzly instance and GitHub OAuth organization.
